<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.vinisebold</groupId>
    <artifactId>BetterInteraction</artifactId>
    <version>v1.0</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>hytale-release</id>
            <url>https://maven.hytale.com/release</url>
        </repository>
        <repository>
            <id>hytale-pre-release</id>
            <url>https://maven.hytale.com/pre-release</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.hypixel.hytale</groupId>
            <artifactId>Server</artifactId>
            <version>2026.01.22-6f8bdbdc4</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>manifest.json</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>